name: save_the_world_flutter_app
description: A new Flutter application.

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  firebase_core: ^2.24.0
  url_launcher: ^6.2.1
  share_plus: ^7.2.1
  package_info_plus: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: SaveTheWorldFont
      fonts:
        - asset: assets/fonts/SaveTheWorldFont.ttf

  assets:
    - assets/icons/
