name: save_the_world_flutter_app
description: A new Flutter application.

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  firebase_core: ^2.24.0
  url_launcher: ^6.2.1
  share_plus: ^7.2.1
  package_info_plus: ^4.2.0
  confetti: ^0.7.0
  audio_session: ^0.1.18

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.3.10
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/save_the_world_512.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#ffffff"
  image: assets/icons/save_the_world_512.png
  android_12:
    image: assets/icons/save_the_world_512.png
    color: "#ffffff"
  web: false

flutter:
  uses-material-design: true

  fonts:
    - family: SaveTheWorldFont
      fonts:
        - asset: assets/fonts/SaveTheWorldFont.ttf

  assets:
    - assets/icons/
